service:
    daemon_mode: True
    update_interval: 10
    self_discovery: True
    bind_to_ip: False

mqtt:
    host: mqtt
    port: 1883
    client_id: ac_to_mqtt
    user: koos
    passwd: koos_se_password
    topic_prefix: /aircon
    auto_discovery_topic: homeassistant
    auto_discovery_topic_retain: False
    discovery: False

##Devices
devices:
- ip: 10.2.0.230
  mac: b4222dce73f1
  name: Living Room
  port: 80
- ip: 10.2.0.227
  mac: b4222da741af
  name: Office
  port: 80